"component : angular":
  - changed-files:
      - any-glob-to-any-file:
           - frontend/blog-angular-ui/**/*
"component : quarkus":
  - changed-files:
      - any-glob-to-any-file:
          - quarkus-project/**/*
"component : spring-boot-rest-webmvc":
  - changed-files:
      - any-glob-to-any-file:
          - poc-rest-api/spring-boot-rest-webmvc/**/*
"component : spring-boot-rest-webflux":
  - changed-files:
      - any-glob-to-any-file:
          - poc-rest-api/spring-boot-rest-webflux/**/*
"component : mongodb-redis-integration":
  - changed-files:
      - any-glob-to-any-file:
          - poc-mongodb-redis-cache/mongodb-redis-integration/**/*
"component : reactive-mongodb-redis-integration":
  - changed-files:
      - any-glob-to-any-file:
          - poc-mongodb-redis-cache/reactive-mongodb-redis-integration/**/*
"component : algorithms":
  - changed-files:
      - any-glob-to-any-file:
          - poc-algorithms/**/*
"type: documentation":
  - changed-files:
      - any-glob-to-any-file: 'docs/**/*'
"type: dependency-upgrade":
  - changed-files:
      - any-glob-to-any-file:
          - frontend/blog-angular-ui/pom.xml
          - frontend/blog-angular-ui/package.json
          - frontend/blog-angular-ui/package-lock.json
          - quarkus-project/pom.xml
          - poc-rest-api/spring-boot-rest-webmvc/pom.xml
          - poc-rest-api/spring-boot-rest-webflux/pom.xml
          - poc-mongodb-redis-cache/mongodb-redis-integration/pom.xml
          - poc-mongodb-redis-cache/reactive-mongodb-redis-integration/pom.xml
          - poc-algorithms/pom.xml
