CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 5;

CREATE TABLE ADDRESS (ID BIGINT NOT NULL, COUNTY VARCHAR(255), POSTCODE VARCHAR(255), STREET VARCHAR(255), TOWN VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE CUSTOMER (ID BIGINT NOT NULL, DATE_OF_BIRTH TIMESTAMP, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), ADDRESS_ID BIGINT, PRIMARY KEY (ID), CONSTRAINT FK_ADDRESS_ID FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID) );
