CREATE SEQUENCE HIBERNATE_SEQUENCE 
  START WITH 1 
  INCREMENT BY 5; 

CREATE TABLE CUSTOMER 
  ( 
     ID            BIGINT NOT NULL, 
     DATE_OF_BIRTH TIMESTAMP, 
     FIRST_NAME    VARCHAR(255), 
     LAST_NAME     VARCHAR(255), 
     PRIMARY KEY (ID) 
  ); 

CREATE TABLE ADDRESS 
  ( 
     COUNTY      VARCHAR(255), 
     POSTCODE    VARCHAR(255), 
     STREET      VARCHAR(255), 
     TOWN        VARCHAR(255), 
     CUSTOMER_ID BIGINT NOT NULL, 
     PRIMARY KEY (CUSTOMER_ID), 
     CONSTRAINT FK_ADDRESS_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID) 
  );

CREATE TABLE orders
  (
     ORDER_ID         BIGINT NOT NULL,
     created_on       TIMESTAMP,
     order_number     VARCHAR(255) NOT NULL UNIQUE,
     status           VARCHAR(255),
     CUSTOMER_ID      BIGINT NOT NULL,
     PRIMARY KEY      (ORDER_ID),
     CONSTRAINT FK_ORDER_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
  );
