version: "3"
services:
  mongo:
    image: mongo:8.0.10
    volumes:
      - mongo-data:/data/db/mongo
    ports:
      - 27017:27017

  redis:
    image: redis
    volumes:
      - redis-data:/data/db/redis
    ports:
      - 6379:6379
      
volumes:
  mongo-data:
  redis-data: