version: "3"

services:
  #  Create a service named postgres.
  postgres:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: postgres:15-alpine
    #   Give the container the name postgres. You can change to something else.
    container_name: postgres
    #   Setup the username, password, and database name. You can change these values.
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=rest
    #   Maps port 5432 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - 5432:5432
    #   Set a volume some that database is not lost after shutting down the container.
    #   I used the name postgres-data but you can changed it to something else.
    networks:
      - postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data: