name: blog-angular-ui CI
on:
  push:
    paths:
      - "frontend/blog-angular-ui/**"
    branches:
      - master
  pull_request:
    paths:
      - "frontend/blog-angular-ui/**"
    types:
      - opened
      - synchronize
      - reopened


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '18' ]
    name: Build on Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.2.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
      - name: Build with Maven and analyze
        run: |
          cd frontend
          cd blog-angular-ui
          mvn -B clean package
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0


