name: blog-angular-ui CI
on:
  push:
    paths:
      - "frontend/blog-angular-ui/**"
    branches:
      - main
  pull_request:
    paths:
      - "frontend/blog-angular-ui/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
    defaults:
      run:
        working-directory: "frontend/blog-angular-ui"
    name: Build with Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
          
      - name: Build with Maven
        run: ./mvnw -B clean package -Pnpm


