name: poc-spring-boot-rabbitmq CI
on:
  push:
    paths:
      - "poc-spring-boot-rabbitmq/**"
    branches:
      - master
  pull_request:
    paths:
      - "poc-spring-boot-rabbitmq/**"
    types:
      - opened
      - synchronize
      - reopened


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '18' ]
    name: Build on Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.1.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
      - name: Build with Maven and analyze
        run: |
          cd poc-spring-boot-rabbitmq
          mvn -B clean package --file pom.xml 
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0


