name: poc-spring-boot-rest CI
on:
  push:
    paths:
      - "poc-spring-boot-rest/**"
    branches:
      - master
  pull_request:
    paths:
      - "poc-spring-boot-rest/**"
    types:
      - opened
      - synchronize
      - reopened


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: Build on Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.5.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd poc-spring-boot-rest
          mvn -B clean package --file pom.xml 
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0


